version: 2
updates:
    # GitHub Actions updates
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: weekly
      groups:
          github-actions:
              patterns:
                  - "*"

    # UV Python project dependencies (pyproject.toml + uv.lock)
    - package-ecosystem: uv
      directory: "/"
      schedule:
          interval: weekly

    # Documentation dependencies (separate from main project)
    - package-ecosystem: pip
      directory: "/docs"
      schedule:
          interval: weekly
