# codecov.yml file, spec is visible:
# https://github.com/codecov/support/wiki/Codecov-Yaml
coverage:
  status:
    project:
      default:
        # coverage may fall by <1% and still be considered "passing"
        threshold: 1%
    # pull-requests only
    patch:
      default:
        # coverage may fall by <1% and still be considered "passing"
        threshold: 1%
