pull_request_rules:
    - name: Merge pull requests from dependabot if CI passes
      conditions:
          - author=dependabot[bot]
          - check-success=pre-commit 3.9 / ubuntu-latest
          - check-success=tests 3.9 / windows-latest
          - check-success=tests 3.9 / ubuntu-latest
          - check-success=tests 3.9 / macos-latest
          - check-success=CodeQL
      actions:
          merge:
              method: squash
    - name: Merge non-draft pull requests from me
      conditions:
          - -draft
          - author=andrewbolster
          - check-success=pre-commit 3.9 / ubuntu-latest
          - check-success=tests 3.9 / windows-latest
          - check-success=tests 3.9 / ubuntu-latest
          - check-success=tests 3.9 / macos-latest
          - check-success=codecov/project
          - check-success=CodeQL
          - check-success=docs-build 3.9 / ubuntu-latest 
          - check-success=xdoctest 3.9 / ubuntu-latest 
          - check-success=typeguard 3.9 / ubuntu-latest 
          - check-success=coverage
      actions:
          merge:
              method: squash

