pull_request_rules:
    - name: Merge pull requests from dependabot if CI passes
      conditions:
          - author=dependabot[bot]
          - check-success=pre-commit 3.9 / ubuntu-latest
          - check-success=tests 3.9 / windows-latest
          - check-success=tests 3.9 / ubuntu-latest
          - check-success=tests 3.9 / macos-latest
          - check-success=codecov/project
      actions:
          merge:
              method: squash