pull_request_rules:
    -   name: Merge pull requests from pyup if CI passes
        conditions:
            - author=pyup-bot
            - status-success=continuous-integration/travis-ci/pr
        actions:
            merge:
                method: squash
                strict: true