comment: false
coverage:
    status:
        project:
            default:
                target: 20%
        patch:
            default:
                target: 50%
                threshold: 20%
ignore:
    - "src/bolster/cli.py"
