#!/usr/bin/env python
"""
Bolster documentation build configuration file for Sphinx.

This configuration file sets up comprehensive documentation generation
with modern Sphinx extensions and best practices for API documentation,
examples, and cross-references.
"""

import os
import sys
from datetime import datetime

# Add the source directory to Python path for autodocumentation
sys.path.insert(0, os.path.abspath("../src"))

import bolster  # noqa: E402

# -- General configuration ---------------------------------------------

# Minimum Sphinx version required
needs_sphinx = "4.0"

# Sphinx extensions for comprehensive documentation generation
extensions = [
    # Core autodoc extensions
    "sphinx.ext.autodoc",  # Automatic documentation from docstrings
    "sphinx.ext.autosummary",  # Generate summaries of modules/classes
    "sphinx.ext.viewcode",  # Add source code links
    "sphinx.ext.napoleon",  # Support for Google/NumPy style docstrings
    "sphinx.ext.autodoc.typehints",  # Automatic type hints documentation
    # API documentation
    "autoapi.extension",  # Automatic API documentation generation
    # Cross-referencing and linking
    "sphinx.ext.intersphinx",  # Link to other project's documentation
    "sphinx.ext.extlinks",  # Markup for external links
    # Code and testing
    "sphinx.ext.doctest",  # Test code snippets in documentation
    "sphinx.ext.coverage",  # Documentation coverage reports
    # Mathematical content
    "sphinx.ext.mathjax",  # Render math via JavaScript
    # Development and debugging
    "sphinx.ext.todo",  # Support for todo items
    "sphinx.ext.ifconfig",  # Include content based on configuration
    # Visualization and inheritance
    "sphinx.ext.inheritance_diagram",  # Create inheritance diagrams
    "sphinx.ext.graphviz",  # Support for Graphviz diagrams
    # External tool integration
    "sphinx_click.ext",  # Document Click CLI applications
    "sphinx_issues",  # Link to GitHub issues/PRs
    "nbsphinx",  # Jupyter notebook integration
    "sphinx_github_changelog",  # Generate changelog from GitHub
    "sphinxcontrib.apidoc",  # Enhanced API documentation
    # Output formats and publishing
    "sphinx.ext.githubpages",  # Publish to GitHub Pages
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Bolster"
current_year = datetime.now().year
copyright = f"2017-{current_year}, Andrew Bolster"
author = "Andrew Bolster"

# GitHub configuration
github_user = "andrewbolster"
github_project = project.lower()
github_stub = f"{github_user}/{github_project}"
github_root = f"https://github.com/{github_stub}/"
github_doc_root = f"{github_root}tree/main/docs/"

# Extension configurations
issues_github_path = github_stub

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = bolster.__version__
# The full version, including alpha/beta/rc tags.
release = bolster.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = "sphinx_rtd_theme"

# Theme-specific configuration for improved UX
html_theme_options = {
    "canonical_url": "",
    "analytics_id": "",
    "analytics_anonymize_ip": False,
    "logo_only": False,
    "display_version": True,
    "prev_next_buttons_location": "bottom",
    "style_external_links": False,
    "vcs_pageview_mode": "",
    "style_nav_header_background": "#2980B9",
    # Toc options
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

# The name for this set of Sphinx documents
html_title = f"{project} {release}"

# Custom CSS and JavaScript files
html_static_path = ["_static"]

# Custom sidebar templates
html_sidebars = {
    "**": [
        "relations.html",  # needs 'show_related': True theme option to display
        "searchbox.html",
    ]
}

# -- Options for HTMLHelp output ---------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "bolsterdoc"

# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass
# [howto, manual, or own class]).
latex_documents = [(master_doc, "bolster.tex", "Bolster Documentation", "Andrew Bolster", "manual")]

# -- Options for manual page output ------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "bolster", "Bolster Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "bolster",
        "Bolster Documentation",
        author,
        "bolster",
        "One line description of project.",
        "Miscellaneous",
    )
]

# -- Extension configuration -------------------------------------------------

# -- Options for Autodoc Extension --
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
}
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"
autodoc_mock_imports = []

# -- Options for AutoAPI Extension --
autoapi_modules = {github_project: None}
autoapi_dirs = [f"../src/{github_project}"]
autoapi_type = "python"
autoapi_file_patterns = ["*.py"]
autoapi_generate_api_docs = True
autoapi_add_toctree_entry = False  # We manually control the toctree
autoapi_python_class_content = "both"  # Include both class and __init__ docstrings
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
    "special-members",
    "imported-members",
]

# Suppress some autoapi warnings
autoapi_keep_files = True

# -- Options for Napoleon Extension --
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_use_keyword = True
napoleon_custom_sections = None

# -- Options for Intersphinx Extension --
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "requests": ("https://docs.python-requests.org/en/master/", None),
    "click": ("https://click.palletsprojects.com/en/8.1.x/", None),
    "boto3": ("https://boto3.amazonaws.com/v1/documentation/api/latest/", None),
    "PIL": ("https://pillow.readthedocs.io/en/stable/", None),
}

# -- Options for Todo Extension --
todo_include_todos = True
todo_emit_warnings = True

# -- Options for Coverage Extension --
coverage_show_missing_items = True

# -- Options for External Links --
extlinks = {
    "issue": (f"{github_root}issues/%s", "issue %s"),
    "pr": (f"{github_root}pull/%s", "PR %s"),
}

# -- Options for Sphinx Click Extension --
sphinx_click_commands = {
    "bolster": {
        "module": "bolster.cli",
        "command": "cli",
    },
}
