name: Bot Pull Request Approve and Merge
# Supports: Dependabot, Pyup.io, Renovate, and other trusted bots
# src: https://blog.somewhatabstract.com/2021/10/11/setting-up-dependabot-with-github-actions-to-approve-and-merge/

on: pull_request_target

permissions:
    pull-requests: write
    contents: write

jobs:
    auto-merge-bot-prs:
        runs-on: ubuntu-latest
        # Support multiple trusted bots
        if: |
            github.actor == 'dependabot[bot]' ||
            github.actor == 'pyup-bot' ||
            github.actor == 'renovate[bot]' ||
            github.actor == 'github-actions[bot]'
        steps:
            # Fetch Dependabot metadata (only for Dependabot PRs)
            - name: Dependabot metadata
              id: dependabot-metadata
              if: github.actor == 'dependabot[bot]'
              uses: dependabot/fetch-metadata@v2.4.0
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"

            # Approve the PR
            - name: Approve bot PR
              run: gh pr review --approve "$PR_URL"
              env:
                  PR_URL: ${{ github.event.pull_request.html_url }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # Enable auto-merge (will only merge when all checks pass)
            - name: Enable auto-merge for bot PRs
              # For Dependabot: skip major updates (uncomment line below if desired)
              # if: github.actor != 'dependabot[bot]' || steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'
              run: gh pr merge --auto --squash "$PR_URL"
              env:
                  PR_URL: ${{ github.event.pull_request.html_url }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
