name: Release

on:
    - push
    - pull_request

jobs:
    notebooks:
        name: Notebooks
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v5
            with:
                fetch-depth: 0
          - name: Set up Python ${{ env.python-version }}
            uses: actions/setup-python@v6
            with:
                python-version: ${{ env.python-version }}
          - name: Install uv and set the python version
            uses: astral-sh/setup-uv@v7
            with:
                python-version: ${{ env.python-version }}
                enable-cache: true
                cache-dependency-glob: "uv.lock"

          - name: Install the project
            run: uv sync --all-extras --dev

          - name: Run notebooks tests
            run: |
              uv run pytest --nbmake --no-cov notebooks/test_*.ipynb
