name: Bump version and push tag

env:
  python-version: 3.13

on:
  # schedule:
  #   - cron: '0 8 * * *'
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ env.python-version }}
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
            python-version: ${{ env.python-version }}
            enable-cache: true
            cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests --cov-branch --cov-report=xml --cov=bolster --cov --junitxml=junit.xml -o junit_family=legacy

      - name: Check code coverage
        run: uv run coverage report --fail-under=80

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: patch
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"

      - name: Push changes
        run: |
          git push origin main --tags
